### ISSUE TITLE
Server Response Time 

### ISSUE THREAD

**Issue by silicahd** [ionos-deploy-now/ionos-deploy-now#132]
We are testing a laravel application. Laravel 10 with PHP 8.3. The front page only has 2 queries and the server response time is 1,530 ms - 1,610 ms . This is not a very good response time in terms of google speed checks.

**Comment by ionos-deploy-now-support** [comment]
Thank you for your feedback regarding the response time of your Laravel application on the DeployNow portal.

In this case, the slower server response time is likely due to the specific contents of your project. In our tests with a sample Laravel project in the same environment, the server response time was consistently under 500ms.
