### ISSUE TITLE
BUG-FIX-REQUEST: secret is missing a trailing 's'

### ISSUE THREAD

**Issue by RamiroPastor** [ionos-deploy-now/ionos-deploy-now#31]
### The problem:

While creating a new Deploy-Now project, I introduced 2 environment variables, and marked them as "secret" using the Deploy-Now user interface, by clicking on the "incognito man" found just at the right end of the variable input.

The GithubActions / Deploy Now reports this error:

```
The workflow is not valid. .github/workflows/deploy-now.yaml (Line: 41, Col: 35): Unrecognized named-value: 'secret'. Located at position 1 within expression: secret.INTERNAL_EMAIL_ADDRESS .github/workflows/deploy-now.yaml (Line: 42, Col: 36): Unrecognized named-value: 'secret'. Located at position 1 within expression: secret.INTERNAL_EMAIL_PASSWORD
```

This error is solved if I manually edit the `.github/workflows/deploy-now.yaml` file and add a trailing 's' to 'secret'

### My requests:

1. Fix the bug.
2. Improve the user interface on the ionos Deploy Now platform so that I can edit all the information I introduced while creating the project, so that I don't have to meddle with the `deploy-now.yaml` file directly (or delete and recreate the project if I did not introduce the correct info)
3. (Very closely related to the 2nd request) Allow me to **somehow** add new **secret variables**: I can modify the `deploy-now.yaml` file to add new variables (as long as I have at least one variable to know where and how to write the info in the file) but **secret variables** cannot be added this way, as far as I can understand.
4. Imburse me for this "developer work" I just did by extending the time of the Static Project I JUST **BOUGHT** to 2032 with no additional charge.

Thanks

**Comment by coder-hugo** [comment]
Hi @RamiroPastor,

thanks for your request. We apologize for any inconveniences you had with IONOS Deploy Now. We have fixed the bug so for all new projects the secrets in the workflow files will be rendered properly.

We understand that you had trouble to adapt the `deploy-now.yaml` and we will think about some improvements. But since the workflow is part of the git repository and can be modified completely by the user (e.g. adding/removing actions), it is nearly impossible for us to change this file without destroying changes that were done by the user manually.

If you want to add a new secret you can do this in the settings area of your git repository. [Here](https://docs.github.com/en/actions/security-guides/encrypted-secrets) you can find more information about the creation of secrets.


Kind regards,

Robin
