### ISSUE TITLE
Tailwind CSS deploy now

### ISSUE THREAD

**Issue by umit-one** [ionos-deploy-now/ionos-deploy-now#46]
Hi,
I have a static site with Tailwind and I'm struggling to deploy it.
I don't quite understand if I should add the dist folder (that only contains the output.css) or the folder that has the HTML files.
I also don't quite get if I should pick nodeJS or command-line. 
The documentation wasn't helping.
Thanks in advance.

**Comment by hunsalz** [comment]
Hi @umit-one,

I just saw your issue and it seems you could accomplish to deploy you site in meanwhile. Congrats!

Due to the fact that you site is static (contains only html, css, js files) no build instructions are needed. The sources need just to transferred from GitHub to IONOS.

But this fact should be described better in the documentation. Thx for addressing this point.
