### ISSUE TITLE
Unable to connect a second Ionos account on Github

### ISSUE THREAD

**Issue by tamoroso** [ionos-deploy-now/ionos-deploy-now#6]
Hi there 👋, 

I already have a Ionos account connected to my GitHub repository. I want to connect an another Ionos account to my GitHub.

When hitting the button connect GitHub, I'm redirected to GitHub app permissions. Then, I updated my permissions and being redirected to Ionos Deploy Now. But nothing happens and I'm stuck in the connect GitHub step with a 409 server error on the console as you can see in the picture.

![image](https://user-images.githubusercontent.com/51746398/153611719-6a7a4fcb-6e6b-427b-b1a7-ec288a305262.png)

Is there any workaround to connect one github account to two differents Ionos account? 

Keep up your great work 💪

**Comment by hunsalz** [comment]
Hi @tamoroso, Deploy Now is designed to have a one-to-one relation with one GitHub-Account. From a technical point of view it keeps the integration straight forward. For example we don't want to dispatch webhook events between different IONOS accounts. - From a product view we give away service for free in the smallest package. I think, it's comprehensible that we don't want to give this free service unlimited - At least not that easy.

But definitely we should improve our error handling and catch the exception in the UI properly. Additional we should add description about this restriction in our document.

Thx for asking this question.

**Comment by coder-hugo** [comment]
Hi @tamoroso,

it isn't possible to install a Github-App twice in one Github account which means you can't connect a single Github account with 2 IONOS accounts.
I'd suggest you to create a Github organization and connect this with your second IONOS account. With this you kind of connect one Github account with 2 IONOS accounts since you can manage the Github organization with the same Github account. Additionally this provides you a better separation of the projects connected to Deploy Now also on Github.

But definitely we should improve our error handling and catch the exception in the UI properly. Additional we should add a description about this restriction in our documentation.

Thx for asking this question.
